# Generated by Django 3.1.1 on 2022-03-22 05:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220322_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='route',
            field=models.CharField(default=django.utils.timezone.now, max_length=240),
            preserve_default=False,
        ),
    ]
