# Generated by Django 3.1.1 on 2022-03-22 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_profiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profiles',
            new_name='Profile',
        ),
    ]
