# Generated by Django 3.1.1 on 2022-03-22 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220322_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='text',
            new_name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.CharField(default=django.utils.timezone.now, max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=240),
            preserve_default=False,
        ),
    ]
