# Generated by Django 3.1.1 on 2022-03-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20220330_1940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
