# Generated by Django 3.1.1 on 2022-03-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('car_name', models.CharField(max_length=120)),
                ('date_of_trip', models.DateField()),
                ('source', models.CharField(max_length=120)),
                ('destination', models.CharField(max_length=120)),
                ('vacant_seats', models.CharField(max_length=120)),
                ('route', models.CharField(max_length=120)),
                ('participants', models.CharField(max_length=120)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
