# Generated by Django 3.1.1 on 2022-04-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20220405_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_of_trip',
            field=models.DateField(null=True),
        ),
    ]
