# Generated by Django 3.1.1 on 2022-04-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20220405_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='vacant_seats',
            field=models.IntegerField(),
        ),
    ]
